sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rGLHhOrW6EyE5440v0BhWt2H/FIlU4sbNL2Hjo4Lx/aZQKgS+afICTrY0NDQBrM3Q2xgjJU/FRDerrVuVekIMEv807QMghRY5cQRTuLGGiihnjz3/CzIuSWs54YCSsZfiD6y5wsZ8rBZh233U8IMBFK5HUhTzl0uUCDPkKUApZjX3wKnsTpixxgkocb/MAw+C7OYOk7mn5TmFlF4I7kmCJCPRDtutgPViVvthw5pkUY76ziFmRhhw33u6gda1aW2emql1xa9yqlFy1oqgDwHmbcl1tm8q8E0uzOAtp2Kp8G+/ADJQlksGYu9R5nKDjhNOZnsTuSLhXvBXYpeg6UoietYYlwOeeF3T2h5v3GssLy9WYfCvmQOqy7vPJyc1KDrdXRXYLF3+JkOUrEm/G0tmHTVkGBnB7nVElf8JOPpLzokJOdLMW8aiqF0mDU7aIO9qVXyvambXraOBjkuPpRD5a3B1Q7yvhLgj34J0Uik07oFkFccXJF4P8iBs5jwT/V15SggIwZKsYpZASzZqPJByUJogz/BtzobA0Qj0LqhM1Tb8JmLjYzh52FOM2Djl5KOJucIMtbYE6KKZpzrV3t9Rdb+Fh2CjmyK949Jo4MrlrztuKEwHSwWj+bhpHt2UKvYsNEwqyxFUj1jcCSSEWdWl3x18KXBOjs4T1oD1aNDAXI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Frozen-Deep_1625
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy